earthblog/blog_posts/forms.py
# blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Content',validators=[DataRequired()])
    submit = SubmitField('Write')

earthblog/blog_posts/views.py
# blog_posts/views.py

from flask import render_template,url_for,flash,request,redirect,Blueprint
from flask_login import current_user,login_required
from earthblog import db
from earthblog.models import BlogPost
from earthblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/write',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data, text=form.text.data,
                                user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('blog has been posted')
        return redirect(url_for('core.index'))
    return render_template('write.html',form=form)

@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post)

@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('blog post has been updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html',title='updating',form=form)

@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('blog post deleted')
    return redirect(url_for('core.index'))

earthblog/core/views.py
# core/views.py

from flask import render_template,request,Blueprint
from earthblog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=
    page,per_page=5)
    return render_template('home.html',blog_posts=blog_posts)

@core.route('/activism')
def info():
    return render_template('activism.html')

earthblog/users/views.py
# users/views.py

from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from earthblog import db
from earthblog.models import User,BlogPost
from earthblog.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from earthblog.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('thanks for registering!')
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)

@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.validate_password(form.password.data) and user is not None:
            login_user(user)
            flash('Log in Success!')
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('blog_posts.create_post')
            return redirect(next)
    return render_template('login.html',form=form)

@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('your user account updated!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

earthblog/templates/account.html
{% extends 'base.html' %}
{% block content %}

<img src="{{url_for('static',filename='headers/gilberto-parada-I9jwwRKKcAM-unsplash.jpg')}}"
style="width:100%;height:10%" alt="first">

<div class="jumbotron jumbotron-fluid">
  <h1 style='font-size:50px'>Tell us about yourself.</h1>
  <h5 style='color:white'>@{{current_user.username}} | {{current_user.email}} | activist #{{current_user.id}}</h5>
  <br>
  <img style="border-radius:100%" align='center' height='350' width='350' src="{{url_for('static',filename='profile_pics/'+
  current_user.profile_image)}}">
</div>

<div class="container">
  <br>
  <h4 style='color:#1F4068'>Update your information below:</h4>
  <br><br>
  <form method="POST" action="" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <div class="form-group">
      <h6>
      {{form.username.label(class='form-group', style='color:#1F4068')}} {{form.username(class='form-control text-center', style='width:400px')}}
      <br>
      {{form.email.label(class='form-group', style='color:#1F4068')}} {{form.email(class='form-control text-center', style='width:400px')}}
      <br>
      {{form.picture.label(class='form-group', style='color:#1F4068')}} {{form.picture(class='form-control', style='width:235px;height:45px')}}
      <br>
      </h6>
      {{form.submit(class='btn btn-success')}}
    </div>
</div>

<br><br>

{% endblock %}

earthblog/templates/activism.html
{% extends 'base.html' %}
{% block content %}

<img src="{{url_for('static',filename='headers/boris-misevic-XjG5ivYsYc8-unsplash.jpg')}}"
style="width:100%;height:10%" alt="first">

<div class="jumbotron jumbotron-fluid">
  <h1 style='font-size:65px'>Let's save our planet.</h1>
  <h5 style=color:#FFFFFF>Here's what <i>we</i> can do:</h5>
</div>

<br>

<div class="container">
  <p style="font-size:20px; margin-left:130px; margin-right:130px">

  </p>
</div>

<br>

<img style='border-radius:15px; filter: drop-shadow(0px 0px 6px #99AFDA)' src="{{url_for('static',filename='carousel/noaa-Om82WVFDHLA-unsplash.jpg')}}" class="d-block w-50" alt="first">

<br><br>

{% endblock %}

earthblog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Earthblog</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='style.css')}}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <meta charset="utf-8">
  </head>
  <body>
      <div align='center'>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{{url_for('core.index')}}">Earthblog</a>
          <button style="background-color:white" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div style="color:white" class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('core.index')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('core.info')}}">Activism</a>
              </li>

              {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Write</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                </li>
              {% endif %}

            </ul>
          </div>
        </nav>
        {% block content %}
        {% endblock %}
      </div>
  </body>
</html>

earthblog/templates/blog_post.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron jumbotron-fluid">
  <h1 style='font-size:60px;color:white'>"{{title}}"</h1>
  <h5 style='color:#DDF3F5'>Written by @{{post.author.username}}</h5>
  <h6 style='color:#DDF3F5'>Posted on {{post.date.strftime('%B %d, %Y')}}</h6>
</div>

<div style="background-color:white;padding:0px;border-radius:15px" class="container">
  <p>{{post.text}}</p>
</div>

<br><br>

{% if post.author == current_user %}
  <div>
    <button type="button" class="btn btn-success"><a style='color:white' href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">update</a></button>
    <br> <br>
    <button type="button" class="btn btn-danger" data-toggle='modal'
    data-target='#del_modal'>delete</button>
  </div>
{% endif %}

<br><br>

<div class="modal" tabindex="-1" role="dialog" id='del_modal'>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">delete post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>are you sure you want to delete this post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
        <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method='POST'>
          <input class="btn btn-danger" type="submit" value="delete">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

earthblog/templates/home.html
{% extends 'base.html' %}
{% block content %}

<img src="{{url_for('static',filename='headers/john-dancy-GNsuW85JNSE-unsplash.jpg')}}"
style="width:100%;height:10%" alt="first">

<div class="jumbotron jumbotron-fluid">
  <h1 style=font-size:120px>Earthblog.</h1>
  <p style="font-size:27px; color:white">Take a <i>stand</i> for what you <i>believe</i>.</p>
</div>

<br>

<div class="container">
  <p style="font-size:20px; margin-left:130px; margin-right:130px">
    Earthblog is a concept website that brings together activists to fight injustice.
    From the Storming of the Bastille to the March on Washington, we've seen
    throughout history that people can move the world with a sufficiently backed
    and unified voice. Earthblog aims to cultivate an environment where
    every member has the ability to inspire one another with their background
    and origin. Nothing unifies people quite the way a common goal does.
  </p>
</div>

<br><br>

<img style='border-radius:15px; filter: drop-shadow(0px 0px 6px #99AFDA)' src="{{url_for('static',filename='pictures/john-towner-89PFnHKg8HE-unsplash.jpg')}}" class="d-block w-50" alt="first">

<br><br>

<br><br>

<div style="background-color:#3B6978" class="jumbotron jumbotron-fluid">
  <h1>Blog Posts</h1>
</div>

<br>

{% if blog_posts.items %}
  <div class="container">
    {% for post in blog_posts.items %}
      <div class="card">
        <div class="card-body">
          <br>
          <h2><a style=color:#1F4068 class="card-title" href='{{url_for('blog_posts.blog_post',
          blog_post_id=post.id)}}'>{{post.title}}</a></h2>
          <br>
          <p style=color:#1F4068>Written by: <a style=color:#17706E href="{{url_for('users.user_posts',username=post.author.username)}}">@{{post.author.username}}</a></p>
          <p style=color:#1F4068>Posted on: {{post.date.strftime('%B %d, %Y')}}</p>
          <br>
          <a class="btn btn-primary" style='background-color:#17706E;border-color:#17706E' href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">Read</a>
          <br><br>
        </div>
      </div>
    {% endfor %}
    <br><br>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,
        left_current=1,right_current=2) %}
          {% if blog_posts.page == page_num %}
            <li class="page-item disabled">
              <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
  </div>
{% else %}
  <br>
  <h6 style=color:#1F4068><i>there are currently no writings to display.</i></h6>
  <br><br>
{% endif %}

<br><br>

{% endblock %}

earthblog/templates/login.html
{% extends 'base.html' %}
{% block content %}

<img src="{{url_for('static',filename='headers/casey-horner-1Mknoq9KnOI-unsplash.jpg')}}"
style="width:100%;height:10%" alt="first">

<div class="jumbotron jumbotron-fluid">
  <h2 style='color:white'><b>Sign in</b> to <i>blog up</i>.</h2>
  <h6 style='color:white'>Let your mind wander.</h6>
</div>

<div class="container">
  <form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
      {{form.email.label(class='form-group')}} {{form.email(class='form-control text-center', style='width:400px')}}
    </div>
    <div class="form-group">
      {{form.password.label(class='form-group')}} {{form.password(class='form-control text-center', style='width:400px')}}
    </div>
    <div class="form-group">
      {{form.submit(class='btn btn-primary')}}
    </div>
  </form>
</div>

{% endblock %}

earthblog/templates/register.html
{% extends 'base.html' %}
{% block content %}

<img src="{{url_for('static',filename='headers/abhas-mishra-J8RMiq7cYN4-unsplash.jpg')}}"
style="width:100%;height:10%" alt="first">

<div class="jumbotron jumbotron-fluid">
  <h2 style='color:white'><b>Sign up</b> to share your <i>vision</i>.</h2>
  <h6 style='color:white'>Please provide the following information:</h6>
</div>

<div class="container">
  <form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
      {{form.email.label(class='form-group')}} {{form.email(class='form-control text-center', style='width:400px')}}
    </div>
    <div class="form-group">
      {{form.username.label(class='form-group')}} {{form.username(class='form-control text-center', style='width:400px')}}
    </div>
    <div class="form-group">
      {{form.password.label(class='form-group')}} {{form.password(class='form-control text-center', style='width:400px')}}
    </div>
    <div class="form-group">
      {{form.pass_confirm.label(class='form-group')}} {{form.pass_confirm(class='form-control text-center', style='width:400px')}}
    </div>
    <div class="form-group">
      {{form.submit(class='btn btn-primary')}}
    </div>
  </form>
</div>

<br><br>

{% endblock %}

earthblog/templates/user_blog_posts.html
{% extends 'base.html' %}
{% block content %}

<img src="{{url_for('static',filename='headers/paul-rysz-EE6RhhcpY4c-unsplash.jpg')}}"
style="width:100%;height:10%" alt="first">

<div class="jumbotron jumbotron-fluid">
  <h1 style='font-size:50px'>@{{user.username}}'s blog</h1>
  <p style='color:white'>{{user.email}} | activist #{{user.id}}</p>
  <br>
  <img style="border-radius:100%" align='center' height='350' width='350' src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
</div>

<br>

{% for post in blog_posts.items %}
  <div class="container">
    <ul class="list-group">
      <li class="list-group-item">
        <div class="container">
          <br>
          <h2><a style=color:#1F4068 class="card-title" href='{{url_for('blog_posts.blog_post',
          blog_post_id=post.id)}}'>"{{post.title}}"</a></h2>
          <p style=color:#1F4068;text-transform:lowercase>posted on: {{post.date.strftime('%B %d, %Y')}}</p>
          <a class="btn btn-primary" style='background-color:#17706E;border-color:#17706E' href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">read post</a>
          <br><br>
        </div>
      </li>
    </ul>
  </div>
{% endfor %}

<br><br>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,
    left_current=1,right_current=2) %}
      {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
          <a class="page-link" href="{{url_for('users.user_posts',username=
          user.username,page=page_num)}}">{{page_num}}</a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="{{url_for('users.user_posts',username=
          user.username,page=page_num)}}">{{page_num}}</a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>

<br><br>

{% endblock %}

earthblog/templates/write.html
{% extends 'base.html' %}
{% block content %}

<img src="{{url_for('static',filename='headers/adriel-kloppenburg-TyWBZWsZSSg-unsplash.jpg')}}"
style="width:100%;height:10%" alt="first">

<div class="jumbotron jumbotron-fluid">
  <h1 style='font-size:50px'>Speak up, @{{current_user.username}}.</h1>
  <h5 style=color:#FFFFFF>Blog your ideas.</h5>
</div>

<div class="container">
  <form class="form-group" method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
      <h6>
        {{form.title.label(class='form-control-label', style='color:#1F4068')}}
        {{form.title(class='form-control form-control text-center', style='width:500px')}}
        <br>
        {{form.text.label(class='form-control-label', style='color:#1F4068')}}
        {{form.text(class='form-control form-control text-center', style='width:500px;height:200px')}}
        <br>
        {{form.submit(class='btn btn-primary', style='background-color:#17706E;border-color:#17706E')}}
      </h6>
    </div>
  </form>
</div>

<br><br>

{% endblock %}